package com.example.atu;

// import com.example.atu.models.Person;
import javafx.beans.binding.Bindings;
import javafx.beans.property.ReadOnlyObjectWrapper;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.value.ObservableValue;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.*;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.util.Callback;

import java.io.*;
import java.net.URL;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.ResourceBundle;

public class MainController implements Initializable {



    @FXML
    private TableView<Person> studentTable;

    @FXML
    private Label totalNumberStudentsLabel;

    @FXML
    private Label K1EnergyLabel;

    @FXML
    private Label K2EnergyLabel;

    @FXML
    private Label K3Tick1Label;

    @FXML
    private Label K3Tick2Label;

    @FXML
    private Label MyPreferenceLabel;

    @FXML
    private Button autoGenerateDataButton;



    @FXML
    void autoGenerateDataButtonPressed(ActionEvent event) {

    }

    private final static ObservableList<Person> person_data = FXCollections.observableArrayList();

    public static final String delimiter = ",";



    /**
     * Initialize the controller.
     *
     * @param location  The location used to resolve relative paths for the root object, or
     *                  {@code null} if the location is not known.
     * @param resources The resources used to localize the root object, or {@code null} if
     *                  the root object was not localized.
     */
    @Override
    public void initialize(URL location, ResourceBundle resources) {
        // Initialization
        String csvFile = "/Users/hw/HKUST/2022-Y3a-Fall/COMP 3111H/Project/COMP3111H-Project/student_data.csv";
        read(csvFile);
        initializeTable();
        initializeStats();


        // Set listeners


    }

    /**
     * Read CSV data into and save the student fields into {@link person_data}.
     *
     * @param csvFile The CSV file.
     */
    public static void read(String csvFile) {

        // System.out.print("\n");
        try {
            File file = new File(csvFile);
            InputStreamReader isr = new InputStreamReader(new FileInputStream(file), "UTF-8");
            BufferedReader br = new BufferedReader(isr);
            String line = " ";
            String[] tempArr;
            br.readLine(); // skip the first line
            while ((line = br.readLine()) != null) {
                tempArr = line.split(delimiter);
                // System.out.println(tempArr[8]);
                System.out.println(tempArr.length);
                System.out.println(tempArr[8]);
                String studentName = tempArr[1]+tempArr[2];
                studentName = studentName.substring(1, studentName.length()-1);
                String studentEmail = tempArr[3];
                studentEmail = studentEmail.substring(1, studentEmail.length()-1);
                String myPreference = tempArr[8].substring(1, tempArr[8].length()-1);
                String concerns = tempArr[9].substring(1, tempArr[9].length()-1);

                person_data.add(new Person(tempArr[0], studentName, studentEmail, tempArr[4], tempArr[5],
                        tempArr[6], tempArr[7], myPreference, concerns));
            }
            br.close();
        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
    }

    /**
     * Initialize {@link studentTable} with fields from {@link person_data}.
     *
     * Override each column's setCellValueFactory() to insert that column's data based on its respective
     * variable in {@link person_data}.
     */
    void initializeTable() {
        studentTable.setEditable(true);
        studentTable.getColumns().get(2).setMinWidth(200);
        studentTable.getColumns().get(3).setMinWidth(200);

        studentTable.setItems(person_data);
        // studentTable.refresh();

        var cols = studentTable.getColumns();
        cols.get(0).setCellValueFactory(new PropertyValueFactory("index"));
        cols.get(1).setCellValueFactory(new PropertyValueFactory("studentid"));
        cols.get(2).setCellValueFactory(new PropertyValueFactory("studentname"));
        cols.get(3).setCellValueFactory(new PropertyValueFactory("email"));
        cols.get(4).setCellValueFactory(new PropertyValueFactory("k1energy"));
        cols.get(5).setCellValueFactory(new PropertyValueFactory("k2energy"));
        cols.get(6).setCellValueFactory(new PropertyValueFactory("k3trick1"));
        cols.get(7).setCellValueFactory(new PropertyValueFactory("k3trick2"));
        cols.get(8).setCellValueFactory(new PropertyValueFactory("mypreference"));
        cols.get(9).setCellValueFactory(new PropertyValueFactory("concerns"));

        studentTable.refresh();





    }

    /**
     * Initialize statistics table.
     */
    void initializeStats() {
        ObservableList<TableColumn<Person, ?>> cols = studentTable.getColumns();
        totalNumberStudentsLabel.setText(String.valueOf(Person.studentIndex));

        Integer myPreferenceCounter = 0;
        Integer K3Tick1Counter = 0;
        Integer K3Tick2Counter = 0;
        List<Integer> K1Energy = new ArrayList<Integer>();
        List<Integer> K2Energy = new ArrayList<Integer>();

        for (Person item : studentTable.getItems()) {
            K3Tick1Counter += ((String) cols.get(6).getCellObservableValue(item).getValue()).equals("1") ? 1 : 0;
            K3Tick2Counter += ((String) cols.get(7).getCellObservableValue(item).getValue()).equals("1") ? 1 : 0;
            K1Energy.add(Integer.parseInt((String) cols.get(4).getCellObservableValue(item).getValue()));
            K2Energy.add(Integer.parseInt((String) cols.get(5).getCellObservableValue(item).getValue()));

            String myPref = (String) cols.get(8).getCellObservableValue(item).getValue();
            myPreferenceCounter += myPref == "" ? 0 : Integer.parseInt(myPref);
        }
        MyPreferenceLabel.setText(myPreferenceCounter.toString());
        K3Tick2Label.setText(String.valueOf(K3Tick2Counter));
        K3Tick1Label.setText(String.valueOf(K3Tick1Counter));
        String avgK2Energy = String.valueOf(K2Energy.stream().mapToInt(Integer::intValue).average().getAsDouble());
        String avgK1Energy = String.valueOf(K1Energy.stream().mapToInt(Integer::intValue).average().getAsDouble());
        Integer minK2Energy = Collections.min(K2Energy);
        Integer maxK2Energy = Collections.max(K2Energy);
        Integer minK1Energy = Collections.min(K1Energy);
        Integer maxK1Energy = Collections.max(K1Energy);
        K2EnergyLabel.setText("(" + avgK2Energy + ", " + minK2Energy + ", " + maxK2Energy + ")");
        K1EnergyLabel.setText("(" + avgK1Energy + ", " + minK1Energy + ", " + maxK1Energy + ")");
    }

    public static class Person {
        private static Integer studentIndex = 0;
        private final SimpleStringProperty index;
        private final SimpleStringProperty studentid;
        private final SimpleStringProperty studentname;

        private final SimpleStringProperty email;
        private final SimpleStringProperty k1energy;
        private final SimpleStringProperty k2energy;
        private final SimpleStringProperty k3trick1;
        private final SimpleStringProperty k3trick2;
        private final SimpleStringProperty mypreference;
        private final SimpleStringProperty concerns;
        private SimpleStringProperty groupID;

        public Person(String student_id, String student_name, String email, String k1_energy, String k2_energy, String k3_trick1,
                      String k3_trick2, String my_preference, String concerns) {
            this.index = new SimpleStringProperty((studentIndex++).toString());
            this.studentid = new SimpleStringProperty(student_id);
            this.studentname = new SimpleStringProperty(student_name);
            this.email = new SimpleStringProperty(email);
            this.k1energy = new SimpleStringProperty(k1_energy);
            this.k2energy = new SimpleStringProperty(k2_energy);
            this.k3trick1 = new SimpleStringProperty(k3_trick1);
            this.k3trick2 = new SimpleStringProperty(k3_trick2);
            this.mypreference = new SimpleStringProperty(my_preference);
            this.concerns = new SimpleStringProperty(concerns);
        }

        public String getEmail() {
            return email.get();
        }

        public SimpleStringProperty emailProperty() {
            return email;
        }

        public void setEmail(String email) {
            this.email.set(email);
        }

        public String getGroupID() {
            return groupID.get();
        }

        public SimpleStringProperty groupIDProperty() {
            return groupID;
        }

        public void setGroupID(String groupID) {
            this.groupID.set(groupID);
        }

        public String getIndex() {
            return index.get();
        }

        public void setIndex(String index) {
            this.index.set(index);
        }

        public String getStudentid() {
            return studentid.get();
        }

        public void setStudentid(String val) {
            studentid.set(val);
        }

        public String getStudentname() {
            return studentname.get();
        }

        public void setStudentname(String val) {
            studentname.set(val);
        }

        public String getK1energy() {
            return k1energy.get();
        }

        public void setK1energy(String val) {
            k1energy.set(val);
        }

        public String getK2energy() {
            return k2energy.get();
        }

        public void setK2energy(String val) {
            k2energy.set(val);
        }

        public String getK3trick1() {
            return k3trick1.get();
        }

        public void setK3trick1(String val) {
            k3trick1.set(val);
        }

        public String getK3trick2() {
            return k3trick2.get();
        }

        public void setK3trick2(String val) {
            k3trick2.set(val);
        }

        public String getMypreference() {
            return mypreference.get();
        }

        public void setMypreference(String val) {
            mypreference.set(val);
        }

        public String getConcerns() {
            return concerns.get();
        }

        public void setConcerns(String val) {
            concerns.set(val);
        }

    }

}

